# Renovate and CI/CD interact with the following line. Keep its format as it is.
ARG NODE_VERSION=24.3.0-alpine3.22@sha256:b8ea75e6dcdf7dbba1ea8b57f77ec89ef04c1719d2ae986c8fbea21f9f4ec187

FROM node:${NODE_VERSION}

RUN apk add --no-cache font-noto font-noto-cjk

# Renovate and CI/CD interact with the following line. Keep its format as it is.
ARG CHROMIUM_VERSION=138.0.7204.93-r0
RUN apk add --no-cache "chromium-swiftshader=${CHROMIUM_VERSION}"
