name: Build

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: none
  packages: none

jobs:
  build-contianer:
    permissions:
      contents: read
      packages: write
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Gather versions
        id: repo
        run: |-
          alpine_version_full="$(grep -e "ALPINE_VERSION=" Dockerfile | cut -d '=' -f 2)"
          alpine_version="${alpine_version_full%@*}"
          chromium_version="$(grep -e "CHROMIUM_VERSION=" Dockerfile | cut -d '=' -f 2)"
          echo "alpine_version_full=$alpine_version_full" >> "$GITHUB_OUTPUT"
          echo "alpine_version=$alpine_version" >> "$GITHUB_OUTPUT"
          echo "chromium_version=$chromium_version" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Log into ghcr.io
        if: github.event_name == 'push'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64,linux/arm64
          tags: |-
            ghcr.io/${{ github.repository }}:${{ steps.repo.outputs.chromium_version }}-${{ steps.repo.outputs.alpine_version }}
