name: Validate renovate config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/renovate.json5"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/renovate.json5"

permissions:
  contents: none

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      # Needed for logging into vault.
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Validate Renovate Config
        uses: grafana/shared-workflows/actions/validate-renovate-config@726f1a912f45b4807774b76a6d40cbd3fb7a12c0 # validate-renovate-config/v0.1.2
